import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {SafeAreaProvider} from 'react-native-safe-area-context';
import {Artwork,ChoiceMark,MirrorEdge,canonicalMark,type Direction} from './Artwork';
import {VisualFoundation} from '../components/inner-rep/v2/Foundation';
import {WordsInteraction,ContextInteraction,CheckInOffer,TimeframeInteraction} from '../components/inner-rep/v2/Interactions';
import {HonestMirror} from '../components/inner-rep/v2/HonestMirror';
import {nextStep,chosenOption,TIMEFRAME_LABEL,type FlowContext,type StepAnswer} from '../lib/innerRep/v2/contracts';
import {TEMPLATE_BY_ID} from '../lib/innerRep/v2/templates';
import {SAFETY_RESOURCES} from '../lib/innerRep/safety';
import {fixture,engineInsight} from '../review/fixtures';
import wordmark from '../assets/brand/mirar-wordmark.png';
import './style.css';

const concepts={
 aperture:{name:'The revisable window',word:'Aperture',number:'01',kicker:'Mirar / emotional fitness',headline:<>Look within.<br/>Leave room to<br/><em>look again.</em></>,intro:'A small daily practice. Your own words. A reflection you can always revise.',story:['Notice what is yours.','Look again.','Leave room to revise.'],storyCopy:['A response belongs to you. Begin with what feels true, including not knowing.','Your words and a reading of your words are different things. Mirar keeps that boundary visible.','A reflection can be partial. Disagree, correct it, or leave the question open.'],completion:'Keep a little room for this.',mirror:'A reflection. Never the whole picture.',description:'The canonical Mirar silhouette becomes a window between your words and a revisable reading.'},
 weave:{name:'What we carry forward',word:'Weave',number:'02',kicker:'Emotional fitness / made through practice',headline:<>A moment is yours.<br/>Its meaning<br/><em>can change.</em></>,intro:'Small Inner Reps make room for what is real. The Mirror keeps your choices distinct from its readings.',story:['A moment, in your words.','A reading meets a moment.','Meaning stays revisable.'],storyCopy:['Something you chose is held in your own words, not turned into a label.','A reflection is a separate thread. It does not replace what you said.','A reading can be loosened, corrected or left aside. No unbroken chain to protect.'],completion:'A small thing to carry.',mirror:'A practice with texture.',description:'Within Mirar’s own window, a chosen moment and its possible meaning meet without becoming one claim.'},
 field:{name:'The open reading',word:'Fieldnotes',number:'03',kicker:'Emotional fitness / the art of looking again',headline:<>What you said.<br/>What it might mean.<br/><em>Room between.</em></>,intro:'A clearer view begins by separating your experience from an interpretation of it.',story:['Look at what is here.','Leave room for another reading.','Take the observation into life.'],storyCopy:['Your lived experience is the starting point. Not a personality type.','A reflection can be incomplete. You can correct it.','The point is not to collect notes. It is to live with greater intention.'],completion:'An observation to take outside.',mirror:'An open notebook. Not a verdict.',description:'The actual Mirar mark becomes an annotated reading surface: response, evidence and uncertainty.'},
} as const;
const sample:FlowContext={template:TEMPLATE_BY_ID.foc_settle,frame:'base',captureCooledDown:true,openThreadDomains:[],threadDeclinedDomains:[]};
const reflection=engineInsight();
type Receipt={context:FlowContext;answers:StepAnswer[]};
const directions=Object.keys(concepts) as Direction[];
const baselineUrl=(import.meta as ImportMeta & {env:{VITE_CREATIVE_BASELINE_URL?:string}}).env.VITE_CREATIVE_BASELINE_URL??'http://127.0.0.1:5174/?experience=discover';

function ReviewBar({direction}:{direction?:Direction}){
 return <aside className="review-bar" aria-label="Creative review controls"><a href="/">Creative review</a><span>Isolated concepts · nothing is saved</span><nav aria-label="Compare creative directions">{directions.map(d=><a key={d} href={`?direction=${d}`} aria-current={direction===d?'page':undefined}>{concepts[d].number} {concepts[d].word}</a>)}</nav></aside>;
}
function Brand(){return <img className="wordmark" src={wordmark as string} alt="Mirar" width="112" height="40"/>;}
function Gallery(){return <><ReviewBar/><main id="main" className="gallery"><Brand/><div className="gallery-heading"><p className="eyebrow">Mirar / three creative worlds</p><h1>How should emotional<br/>fitness <em>feel?</em></h1><p>Three working explorations. One unchanged intelligence architecture.</p></div><div className="concept-grid">{directions.map(d=><a className={`concept-card ${d}`} key={d} href={`?direction=${d}`}><div className="thumb"><Artwork direction={d} phase={d==='weave'?1:0} small/></div><p className="eyebrow">Direction {concepts[d].number} / {concepts[d].word}</p><h2>{concepts[d].name}</h2><p>{concepts[d].description}</p><span className="text-link">Explore the prototype <span aria-hidden="true">↗</span></span></a>)}</div><section className="gallery-note"><h2>My recommendation: Aperture.</h2><p>The revisable Mirar window joins the real mark to the product’s central promise: your response belongs to you; a reading stays open to correction. Use Fieldnotes’ provenance discipline without borrowing another visual identity.</p><a href={baselineUrl} className="text-link">Compare the existing experience ↗</a></section><p className="fineprint">Concepts, not production UI. Samples use approved engine templates. Mirror history is illustrative and explicitly labelled. No sign-in, storage, analytics or network service.</p></main></>;}

function Story({direction}:{direction:Direction}){
 const c=concepts[direction];const [phase,setPhase]=useState(0);
 return <section className="story-section" id="story" aria-labelledby="story-title"><div className="story-art"><Artwork direction={direction} phase={phase}/><p className="art-caption">Mirar’s canonical silhouette · a window, not a measurement</p></div><div className="story-content"><p className="eyebrow">The practice / explore the metaphor</p><h2 id="story-title">{direction==='aperture'?<>Your words.<br/>An open reading.</>:direction==='weave'?<>A moment is yours.<br/>Meaning stays open.</>:<>Look within.<br/>Keep the distinction.</>}</h2><div className="story-controls" role="group" aria-label="Explore the practice">{c.story.map((title,i)=><button key={title} className="story-control" aria-pressed={phase===i} onClick={()=>setPhase(i)}><span className="index" aria-hidden="true">0{i+1}</span><span>{title}</span><span aria-hidden="true">{phase===i?'−':'+'}</span></button>)}</div><p className="story-caption" aria-live="polite">{c.storyCopy[phase]}</p><a className="text-link" href="#practice">Try it for yourself <span aria-hidden="true">↓</span></a></div></section>;
}

function ChoiceStep({step,direction,answer}:{step:Extract<ReturnType<typeof nextStep>,{type:'choice'}>;direction:Direction;answer:(value:StepAnswer)=>void}){
 const [selected,setSelected]=useState<string|null>(null);const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{heading.current?.focus({preventScroll:true});},[step.id]);
 const options=[...step.options,{id:'__unknown',label:"I don't know"}];
 return <><h3 ref={heading} tabIndex={-1} className="rep-prompt">{step.prompt}</h3><div className={`choice-set ${step.layout}`} role="group" aria-label={step.prompt}>{options.map((o,i)=><button key={o.id} className={`choice ${selected===o.id?'is-selected':''}`} aria-pressed={selected===o.id} aria-label={o.label} onClick={()=>setSelected(o.id)}><ChoiceMark direction={direction} index={i}/><span>{o.label}</span><span className="choice-state">{selected===o.id?'Selected':'Choose this'}</span></button>)}</div><div className="choice-footer"><p>No answer is the better answer.</p><button className="solid" disabled={selected===null} onClick={()=>{if(selected!==null)answer(selected==='__unknown'?{stepId:step.id,kind:'unknown'}:{stepId:step.id,kind:'option',optionId:selected});}}>Continue <span aria-hidden="true">→</span></button></div></>;
}

function SafetyPanel(){return <div className="safety" role="alert"><h3>{SAFETY_RESOURCES.headline}</h3><p>{SAFETY_RESOURCES.body}</p>{SAFETY_RESOURCES.lines.map(line=><p key={line.label}><strong>{line.label}</strong><br/>{line.value}</p>)}</div>;}

function Practice({direction,onReceipt}:{direction:Direction;onReceipt:(receipt:Receipt|null)=>void}){
 const [mode,setMode]=useState('attention');const [started,setStarted]=useState(false);const [answers,setAnswers]=useState<StepAnswer[]>([]);const [safe,setSafe]=useState(false);const [completed,setCompleted]=useState(false);const completion=useRef<HTMLDivElement>(null);
 const context=mode==='attention'?sample:fixture(mode==='action'?'timeframe':'commitment').context;
 const step=nextStep(context,answers);
 const reset=(value:string)=>{setMode(value);setAnswers([]);setCompleted(false);setStarted(false);setSafe(false);onReceipt(null);};
 const answer=(value:StepAnswer)=>{if(answers.some(a=>a.stepId===value.stepId))return;const next=[...answers,value];setAnswers(next);if(!nextStep(context,next)){setCompleted(true);onReceipt({context,answers:next});}};
 useEffect(()=>{if(completed)completion.current?.focus({preventScroll:true});},[completed]);
 const option=chosenOption(context,answers);const label=option&&option!=='unknown'?option.label:null;const timing=answers.find(a=>a.kind==='timeframe');
 return <section className="practice-section" id="practice" aria-labelledby="practice-title"><div className="section-intro"><p className="eyebrow">Today / an actual Inner Rep template</p><h2 id="practice-title">One honest moment.</h2><div className="today-window"><MirrorEdge/><p>Notice.<br/>Choose.<br/>Look again.</p></div><p>The question is an invitation. Your response remains yours.</p></div><div className="practice-workspace"><div className="fixture-switch"><label htmlFor="sample-select">Review a supported interaction</label><select id="sample-select" value={mode} onChange={e=>reset(e.target.value)}><option value="attention">Attention · paired truths</option><option value="action">Small action · timeframe</option><option value="commitment">Commitment · follow-up</option></select></div>
 <div className="practice-body">
 {safe?<SafetyPanel/>:completed?<div className="integration" tabIndex={-1} ref={completion}><p className="eyebrow">Integrate → Live / sample complete</p><div className="completion-art"><Artwork direction={direction} phase={2} small/></div><h3>{concepts[direction].completion}</h3><div className="receipt"><p className="eyebrow">Your response to this sample</p><p className="receipt-question">{nextStep(context,[])?.prompt}</p><blockquote>{label??'I don’t know'}</blockquote>{timing?.kind==='timeframe'&&<p className="receipt-question">{timing.timeframe==='specific_date'?timing.date:TIMEFRAME_LABEL[timing.timeframe]}</p>}<p>{option==='unknown'?'You left room for not knowing. Nothing more needs answering.':option&&option.creates==='commitment'?'Something you chose to carry forward. Its outcome belongs to you.':'Notice once, later today, whether this comes up again. You don’t have to change it.'}</p></div><div className="actions"><a className="solid" href="#mirror">Visit the Mirror <span aria-hidden="true">↗</span></a><button className="quiet" onClick={()=>reset(mode)}>Back to Today</button></div></div>:!started?<div className="practice-invitation"><p className="eyebrow">Sample · nothing is saved</p><h3>{mode==='commitment'?'Something you chose to carry.':'Take a moment. Then take it into your day.'}</h3>{context.commitment&&<p className="commitment-label">Illustrative commitment: {context.commitment.label}</p>}<p>This is an exercise, not a test. “I don’t know” is a real answer.</p><button className="solid" onClick={()=>setStarted(true)}>Begin sample <span aria-hidden="true">→</span></button></div>:step?<div className="active-rep" key={step.id}><p className="eyebrow">{step.id==='primary'?'Notice':'Go a little deeper'} / sample</p>{context.commitment&&<p className="commitment-label">You chose: {context.commitment.label}</p>}
 {step.type==='choice'?<ChoiceStep step={step} direction={direction} answer={answer}/>:step.type==='words'?<WordsInteraction step={step} answer={answer} onSafety={()=>{setSafe(true);setAnswers([]);onReceipt(null);}}/>:step.type==='domain_chips'?<ContextInteraction step={step} answer={answer}/>:step.type==='yes_no'?<CheckInOffer step={step} answer={answer}/>:step.type==='timeframe'?<TimeframeInteraction step={step} answer={answer}/>:<p>This interaction is unavailable in the approved contract.</p>}
 <button className="quiet exit-rep" onClick={()=>reset(mode)}>Leave the sample</button></div>:null}
 </div><p className="sample-privacy">Local sample. No account, saved answers or inferred profile. Optional words are not saved.</p></div></section>;
}

function Mirror({direction,receipt}:{direction:Direction;receipt:Receipt|null}){
 const [view,setView]=useState<'beginning'|'study'>('beginning');const [separate,setSeparate]=useState(false);const [turned,setTurned]=useState(false);const [safe,setSafe]=useState(false);const [version,setVersion]=useState(0);
 const option=receipt?chosenOption(receipt.context,receipt.answers):null;
 const exactLabel=option&&option!=='unknown'?option.label:option==='unknown'?'I don’t know':null;
 return <section className="mirror-section" id="mirror" aria-labelledby="mirror-title"><div className="mirror-heading"><p className="eyebrow">The Mirror / conceptual surface</p><h2 id="mirror-title">{concepts[direction].mirror}</h2><p>A response is something you said. A reflection is a reading you can question.</p></div><div className="mirror-mode" role="group" aria-label="Preview Mirror states"><button aria-pressed={view==='beginning'} onClick={()=>setView('beginning')}>At the beginning</button><button aria-pressed={view==='study'} onClick={()=>setView('study')}>Illustrative future view</button></div>
 {view==='beginning'?<div className="mirror-beginning"><div className="mirror-emblem"><Artwork direction={direction} phase={0} small/></div><div><p className="eyebrow">No interpretation yet</p><h3>You don’t need to be understood before you begin.</h3><p>{exactLabel?'You tried a sample. It hasn’t become a profile or a pattern.':'There is no history in this preview. A small practice is enough to begin.'}</p><a href="#practice" className="text-link">Make room for a moment ↓</a></div></div>:<div className="mirror-study"><p className="illustrative-banner">Illustrative future layout · fictional evidence · not your history. Requires an approved Mirror read model.</p><div className="reading-controls"><span className="eyebrow">The response stays distinct from the reading</span><button className="quiet" aria-pressed={separate} onClick={()=>setSeparate(!separate)}>{separate?'Read alongside':'Read separately'}</button></div><div className={`mirror-columns ${separate?'read-separately':''}`}><article className={`observation-leaf ${turned?'turned':''}`}><MirrorEdge/><p className="eyebrow">{turned?'The limit of this observation':'01 / what was explicitly said'}</p><h3>{turned?'One response isn’t a pattern.':'In your own choice.'}</h3><blockquote>{turned?'No conclusion about who you are.':exactLabel??'I could settle into one thing.'}</blockquote><p>{turned?'The graphic is a visual metaphor. It carries no psychological measurement.':exactLabel?'Exact option from the sample you just tried. Memory-only; not stored.':'Illustrative option from an approved template. No user history.'}</p><button className="quiet" onClick={()=>setTurned(!turned)} aria-pressed={turned}>{turned?'Return to the response':'Turn the observation over'} <span aria-hidden="true">↻</span></button><div className="leaf-mark"><Artwork direction={direction} phase={turned?2:0} small/></div></article><article className="inference-leaf"><MirrorEdge/><p className="eyebrow">02 / what might be reflected</p><p className="fineprint">Engine-generated from five fictional work responses. Separate from your sample. Feedback affects this local demo only.</p>{safe?<SafetyPanel/>:reflection?<HonestMirror key={version} insight={reflection} onFeedback={async()=>{}} onCorrection={async()=>{}} onSafety={()=>setSafe(true)}/>:<p>No reflection available for this fixture.</p>}<button className="quiet reset-mirror" onClick={()=>{setVersion(v=>v+1);setSafe(false);}}>Reset reflection demo</button></article></div><div className="uncertainty"><span className="eyebrow">03 / what remains uncertain</span><p>What has shifted over time is unavailable here. No graphic stands in for missing evidence.</p></div></div>}
 </section>;
}

function Concept({direction}:{direction:Direction}){
 const c=concepts[direction];const [receipt,setReceipt]=useState<Receipt|null>(null);
 return <div className={`concept ${direction}`} style={{'--mirar-mark':`url(${canonicalMark})`} as React.CSSProperties}><ReviewBar direction={direction}/><header className="product-header"><a href="/" aria-label="Mirar creative review home"><Brand/></a><nav aria-label="Prototype sections"><a href="#story">The practice</a><a href="#mirror">The Mirror</a><a className="header-cta" href="#practice">Try an Inner Rep <span aria-hidden="true">↗</span></a></nav></header><main id="main"><section className="hero" aria-labelledby="hero-title"><div className="hero-text"><p className="eyebrow">{c.kicker}</p><h1 id="hero-title">{c.headline}</h1><p className="hero-intro">{c.intro}</p><div className="actions"><a className="solid" href="#practice">Try a moment <span aria-hidden="true">↗</span></a><a className="text-link" href="#story">Meet the practice ↓</a></div><p className="fineprint">No perfect answer. No streak to protect.</p></div><figure className="hero-art"><Artwork direction={direction} phase={direction==='weave'?1:0}/><figcaption>Concept {c.number} / {c.name}<span>Canonical mark · revisable reading</span></figcaption></figure><div className="hero-foot"><span>NOTICE → EXERCISE → INTEGRATE → LIVE</span><span>A daily recalibration, not a destination.</span></div></section><Story direction={direction}/><Practice direction={direction} onReceipt={setReceipt}/><Mirror direction={direction} receipt={receipt}/><section className="closing"><p className="eyebrow">An everyday practice</p><h2>{direction==='field'?'Leave the notebook open.':direction==='weave'?'There is room to begin again.':'Take the noticing. Leave the rest.'}</h2><p>Emotional fitness isn’t always feeling good. It’s becoming more capable of living with whatever you feel.</p><a className="solid" href="#practice">Return to the sample ↗</a><details><summary>Privacy and prototype boundaries</summary><p>No sign-in, emails, analytics or storage. Only local assets and the existing engine contracts are used. Words go through the existing safety check and are cleared. No psychological insights are inferred from your sample. Navigation away resets the preview. This is not therapy or a clinical tool.</p></details></section></main><footer><Brand/><p>Creative exploration {c.number} · {c.word}<br/>Not selected for production.</p><a href="/">Compare the three directions ↗</a></footer></div>;
}
const parameter=new URLSearchParams(location.search).get('direction');const direction=directions.find(d=>d===parameter);
createRoot(document.getElementById('root')!).render(<SafeAreaProvider><VisualFoundation><a className="skip-link" href="#main">Skip to content</a>{direction?<Concept direction={direction}/>:<Gallery/>}</VisualFoundation></SafeAreaProvider>);
