import * as fs from 'fs';
import * as path from 'path';
import { V2, V2Config } from '../../lib/innerRep/v2/config';
import { TEMPLATES } from '../../lib/innerRep/v2/templates';
import { CAPACITIES } from '../../lib/innerRep/v2/types';
import { PROFILES, Profile } from './profiles';
import { Metrics, metrics } from './report';
import { RunResult, runProfile } from './runner';

const SEEDS = Array.from({ length: 20 }, (_, k) => k + 1);
const med = (xs: number[]) => { const s = [...xs].sort((a, b) => a - b); return s.length ? s[Math.floor(s.length / 2)] : NaN; };
const mean = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / Math.max(1, xs.length);
const f = (x: number, d = 1) => (Number.isFinite(x) ? x.toFixed(d) : '—');
const pct = (x: number) => `${Math.round(x * 100)}%`;
const runAll = (ps: Profile[], over: Partial<V2Config> = {}, seeds = SEEDS) => ps.map((p) => ({ p, runs: seeds.map((s) => runProfile({ ...p, seed: p.seed * 1000 + s }, over)) }));

const out: string[] = [];
const P = (...x: string[]) => out.push(...x);
P('# V2 simulator — aggregate analysis', '', `Generated by \`npx tsx scripts/sim/analysis.ts\`. Every profile is run with ${SEEDS.length} different seeds (same synthetic user, different random draws). All figures are from synthetic users and are design evidence, not evidence about real people.`, '');

const p30 = PROFILES.filter((p) => p.days === 30);
const p60 = PROFILES.filter((p) => p.days === 60);
const all30 = runAll(p30); const all60 = runAll(p60);

// ── per-profile table
const row = (p: Profile, ms: Metrics[]) => `| ${p.id} | ${f(mean(ms.map((m) => m.reps)), 0)} | ${f(mean(ms.map((m) => m.rest)))} | ${pct(mean(ms.map((m) => ((m.layers.context ?? 0) + (m.layers.continuity ?? 0)) / Math.max(1, m.reps))))} | ${Math.max(...ms.map((m) => m.maxConsecutiveContext))} | ${Math.max(...ms.map((m) => m.maxThreadReps))} | ${f(mean(ms.map((m) => m.templatesUsed)), 1)} | ${f(med(ms.map((m) => m.earliestExactRepeat ?? 99)), 0)} | ${f(mean(ms.map((m) => m.insights)))} |`;
P('## 1. Per-profile behaviour (mean over seeds unless stated)', '', '| Profile | Reps | No-rep days | Context+continuity share | Max consecutive context reps | Max checks on one thread | Templates used (of 23) | Median earliest exact repeat (day) | Insights shown |', '|---|---|---|---|---|---|---|---|---|');
for (const { p, runs } of [...all30, ...all60]) P(row(p, runs.map(metrics)));
P('');

// ── catalog stress
const catalog = (set: { p: Profile; runs: RunResult[] }[], label: string) => {
  const counts: Record<string, number> = {}; let total = 0; const earliest: number[] = []; const mech: number[] = []; const usedPer: number[] = []; const capShares: Record<string, number[]> = {}; CAPACITIES.forEach((c) => (capShares[c] = []));
  let runsWithMechFatigue = 0, nRuns = 0;
  for (const { runs } of set) for (const r of runs) { const m = metrics(r); nRuns++; for (const [k, v] of Object.entries(m.templateCounts)) { counts[k] = (counts[k] ?? 0) + v; total += v; } if (m.earliestExactRepeat) earliest.push(m.earliestExactRepeat); if (m.earliestMechanismFatigue) { mech.push(m.earliestMechanismFatigue); runsWithMechFatigue++; } usedPer.push(m.templatesUsed); CAPACITIES.forEach((c) => capShares[c].push(m.capShare[c])); }
  P(`### ${label}`, '', `Runs: ${nRuns}. Total reps: ${total}.`, '');
  P(`- **Earliest exact repeat** (same non-continuity exercise + binding): min day ${Math.min(...earliest)}, median day ${f(med(earliest), 0)} (${earliest.length}/${nRuns} runs repeat at all).`);
  P(`- **Earliest mechanism fatigue** (≥3 of any 5 consecutive reps share a mechanism; lens tests counted as one mechanism): ${runsWithMechFatigue}/${nRuns} runs; min day ${mech.length ? Math.min(...mech) : '—'}, median day ${f(med(mech), 0)}.`);
  P(`- **Templates used per run**: mean ${f(mean(usedPer))}, min ${Math.min(...usedPer)}, max ${Math.max(...usedPer)} (of ${TEMPLATES.length}).`);
  P(`- **Capacity balance** (mean share of reps): ${CAPACITIES.map((c) => `${c} ${pct(mean(capShares[c]))}`).join(' · ')}.`);
  const never = TEMPLATES.filter((t) => !counts[t.id]).map((t) => t.id); const rare = TEMPLATES.filter((t) => counts[t.id] && counts[t.id] / total < 0.01).map((t) => `${t.id} (${f((100 * counts[t.id]) / total, 2)}%)`);
  P(`- **Never selected**: ${never.join(', ') || 'none'}. **Under 1% of reps**: ${rare.join(', ') || 'none'}.`, '');
  P('| Template | Role | Share of reps |', '|---|---|---|');
  for (const t of [...TEMPLATES].sort((a, b) => (counts[b.id] ?? 0) - (counts[a.id] ?? 0))) P(`| ${t.id} | ${t.role} | ${f((100 * (counts[t.id] ?? 0)) / total, 1)}% |`);
  P('');
};
P('## 2. Catalog stress (23 templates)', '');
catalog(all30, '30-day runs (all profiles × seeds)');
catalog(all60, '60-day runs (all profiles × seeds)');
// stable-only fatigue
catalog(all30.filter((x) => x.p.id === 'stable'), 'Stable user only (30 days) — the hardest case for repetition, since nothing context-driven varies the menu');

// ── no-rep frequency
P('## 3. "No rep today" frequency', '', '| Profile | Mean no-rep days | Max over seeds | Share of opened days (mean) |', '|---|---|---|---|');
for (const { p, runs } of [...all30, ...all60]) { const ms = runs.map(metrics); P(`| ${p.id} | ${f(mean(ms.map((m) => m.rest)))} | ${Math.max(...ms.map((m) => m.rest))} | ${pct(mean(ms.map((m) => m.rest / Math.max(1, m.opened))))} |`); }
P('');

// ── evidence activity
const kinds: Record<string, number> = {}; const insightKinds: Record<string, number> = {}; const tiers: Record<string, number> = {}; let runsN = 0;
for (const { runs } of [...all30, ...all60]) for (const r of runs) { runsN++; for (const i of r.state.insights) { insightKinds[i.kind] = (insightKinds[i.kind] ?? 0) + 1; tiers[i.tier] = (tiers[i.tier] ?? 0) + 1; } for (const l of r.logs) for (const k of l.newEvidence) { const kk = k.split(':')[0]; kinds[kk] = (kinds[kk] ?? 0) + 1; } }
P('## 4. Evidence and insight activity across all runs', '', `Evidence objects first created: ${JSON.stringify(kinds)}.  \nInsights shown: ${JSON.stringify(insightKinds)}; by wording tier ${JSON.stringify(tiers)}.  \nMean insights per run: ${f(Object.values(insightKinds).reduce((a, b) => a + b, 0) / runsN, 2)}.`, '');

// ── commitments
const cstat: Record<string, number> = {}; const asks: number[] = []; let maxAsk = 0;
for (const { runs } of [...all30, ...all60]) for (const r of runs) for (const c of r.state.commitments) { cstat[c.status] = (cstat[c.status] ?? 0) + 1; asks.push(c.asks); maxAsk = Math.max(maxAsk, c.asks); }
P('## 5. Commitments', '', `Final status across all runs: ${JSON.stringify(cstat)}. Asks per commitment: mean ${f(mean(asks), 2)}, max ${maxAsk} (cap ${V2.commitment.maxAsks} per user-set date).`, '');

// ── returns after gaps
const ret: Record<string, number> = {};
for (const { p, runs } of [...all30, ...all60]) if (['absence_week', 'absence_month_60', 'every_2_3_days'].includes(p.id)) for (const r of runs) { const a = r.state.instances; for (let k = 1; k < a.length; k++) if (a[k].day - a[k - 1].day >= V2.gaps.returnDays) { const key = `${p.id}: ${a[k].intent}`; ret[key] = (ret[key] ?? 0) + 1; } }
P('## 6. First rep after a gap of 7+ days (all seeds)', '', '```', JSON.stringify(ret, null, 1), '```', '');

// ── disagreement
let noCount = 0, afterNoInsights = 0, tentDays = 0, disagreeRuns = 0;
for (const r of all30.find((x) => x.p.id === 'disagrees')!.runs) { disagreeRuns++; const first = r.state.insights.find((i) => i.feedback?.value === 'no'); if (first) { noCount += r.state.insights.filter((i) => i.feedback?.value === 'no').length; afterNoInsights += r.state.insights.filter((i) => i.day > first.day).length; } tentDays += r.logs.filter((l) => l.decision?.trace.constraints.some((c) => c.name === 'tentative mode')).length; }
P('## 7. Disagreement (profile "disagrees": says "No" to every insight)', '', `Over ${disagreeRuns} seeds: ${f(noCount / disagreeRuns, 2)} "No" answers per run; insights shown after the first "No": ${f(afterNoInsights / disagreeRuns, 2)} per run; days spent in tentative mode: ${f(tentDays / disagreeRuns, 1)} per run.`, '');

// ── threshold sensitivity
P('## 8. Threshold sensitivity', '', 'Each row changes one setting and re-runs the profiles most affected (10 seeds). Columns: share of reps driven by context/continuity · worst run of consecutive context reps · mean days until a user-confirmed thread is first tested through a capacity (sel_bias_A) · mean no-rep days (stable_60) · median earliest exact repeat (stable, day) · mean insights per 30 days (work_stress).', '', '| Setting | Ctx share | Max ctx run | Bias-A latency | Stable_60 no-rep | Exact repeat | Insights |', '|---|---|---|---|---|---|---|');
const variants: { name: string; over: Partial<V2Config> }[] = [
  { name: 'baseline', over: {} },
  { name: 'budget cap 2/5, max 1 in a row', over: { budget: { ...V2.budget, cap: 2, maxConsecutive: 1 } } },
  { name: 'budget cap 4/5, max 3 in a row', over: { budget: { ...V2.budget, cap: 4, maxConsecutive: 3 } } },
  { name: 'probe every 5 reps', over: { probe: { ...V2.probe, everyReps: 5 } } },
  { name: 'probe every 10 reps', over: { probe: { ...V2.probe, everyReps: 10 } } },
  { name: 'exercise window 6 reps', over: { templateWindowReps: 6 } },
  { name: 'exercise window 14 reps', over: { templateWindowReps: 14 } },
  { name: 'thread rest after 1 "not this"', over: { thread: { ...V2.thread, negStreakToRest: 1 } } },
  { name: 'thread rest after 3 "not this"', over: { thread: { ...V2.thread, negStreakToRest: 3 } } },
  { name: 'thread check every 2 reps', over: { thread: { ...V2.thread, checkEveryReps: 2 } } },
  { name: 'thread check every 5 reps', over: { thread: { ...V2.thread, checkEveryReps: 5 } } },
  { name: 'commitment max asks 1', over: { commitment: { ...V2.commitment, maxAsks: 1 } } },
  { name: 'rest min gap 5 days', over: { rest: { ...V2.rest, minGapDays: 5 } } },
];
const S10 = SEEDS.slice(0, 10);
for (const v of variants) {
  const ctxRuns = runAll(PROFILES.filter((p) => ['work_stress', 'relationship_conflict', 'family_past', 'money_future'].includes(p.id)), v.over, S10).flatMap((x) => x.runs).map(metrics);
  const lat = runAll(PROFILES.filter((p) => p.id === 'sel_bias_A'), v.over, S10).flatMap((x) => x.runs).map((r) => { const i = r.state.instances.find((q) => q.capacity === 'relationships' && q.intent.includes(':partner')); return i ? i.day + 1 : 31; });
  const st = runAll(PROFILES.filter((p) => p.id === 'stable_60'), v.over, S10).flatMap((x) => x.runs).map(metrics);
  const st30 = runAll(PROFILES.filter((p) => p.id === 'stable'), v.over, S10).flatMap((x) => x.runs).map(metrics);
  const ws = runAll(PROFILES.filter((p) => p.id === 'work_stress'), v.over, S10).flatMap((x) => x.runs).map(metrics);
  P(`| ${v.name} | ${pct(mean(ctxRuns.map((m) => ((m.layers.context ?? 0) + (m.layers.continuity ?? 0)) / Math.max(1, m.reps))))} | ${Math.max(...ctxRuns.map((m) => m.maxConsecutiveContext))} | ${f(mean(lat))} | ${f(mean(st.map((m) => m.rest)))} | ${f(med(st30.map((m) => m.earliestExactRepeat ?? 99)), 0)} | ${f(mean(ws.map((m) => m.insights)), 1)} |`);
}
P('');
// ── commitment follow-up distribution, budget off vs on
const dist = (over: Partial<V2Config>) => { let runs = 0, reps = 0, total = 0, over3 = 0, w3 = 0, w5 = 0; const gaps: Record<string, number> = {}; const per: number[] = []; const asks: number[] = []; const states: Record<string, number> = {};
  for (const p of PROFILES) for (const sd of SEEDS) { const r = runProfile({ ...p, seed: p.seed * 1000 + sd }, over); runs++; const a = r.state.instances.filter((i) => i.completed); reps += a.length; const cc = a.map((i) => (i.frame === 'commitment_check' ? 1 : 0)); const n = cc.reduce((x: number, y: number) => x + y, 0); total += n; per.push(n);
    for (let k = 0; k + 3 <= cc.length; k++) { const c = cc[k] + cc[k + 1] + cc[k + 2]; w3 = Math.max(w3, c); if (c > 1) over3++; } for (let k = 0; k + 5 <= cc.length; k++) w5 = Math.max(w5, cc[k] + cc[k + 1] + cc[k + 2] + cc[k + 3] + cc[k + 4]);
    let last = -1; cc.forEach((v: number, k: number) => { if (v) { if (last >= 0) { const g = Math.min(k - last, 10); gaps[String(g)] = (gaps[String(g)] ?? 0) + 1; } last = k; } });
    for (const c of r.state.commitments) { asks.push(c.asks); states[c.status] = (states[c.status] ?? 0) + 1; } }
  per.sort((a, b) => a - b); return { runs, reps, total, over3, w3, w5, gaps, per, asks, states }; };
const off = dist({ commitment: { ...V2.commitment, followUpBudget: { perReps: 3, max: 99 } } }); const on = dist({});
const gp = (g: Record<string, number>) => ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'].map((k) => `${k === '10' ? '10+' : k}: ${g[k] ?? 0}`).join(' · ');
P('## 9. Commitment follow-up distribution (budget: at most 1 in any 3 completed reps)', '', `All ${on.runs} runs (${PROFILES.length} profiles × ${SEEDS.length} seeds, includes the multi-commitment profile).`, '', '| | Before (no follow-up budget) | After (1 per 3 reps) |', '|---|---|---|', `| Commitment checks, total | ${off.total} (${f((100 * off.total) / off.reps)}% of reps) | ${on.total} (${f((100 * on.total) / on.reps)}% of reps) |`, `| Per run: median / max | ${off.per[Math.floor(off.per.length / 2)]} / ${off.per[off.per.length - 1]} | ${on.per[Math.floor(on.per.length / 2)]} / ${on.per[on.per.length - 1]} |`, `| Worst count in any 3 consecutive reps | ${off.w3} | ${on.w3} |`, `| Worst count in any 5 consecutive reps | ${off.w5} | ${on.w5} |`, `| 3-rep windows with more than one check | ${off.over3} | ${on.over3} |`, `| Reps between consecutive checks (gap in reps) | ${gp(off.gaps)} | ${gp(on.gaps)} |`, `| Asks per commitment: mean / max | ${f(mean(off.asks), 2)} / ${Math.max(...off.asks)} | ${f(mean(on.asks), 2)} / ${Math.max(...on.asks)} |`, `| Final commitment states | ${JSON.stringify(off.states)} | ${JSON.stringify(on.states)} |`, '');
fs.writeFileSync(path.join(__dirname, '../../docs/V2_ANALYSIS.md'), out.join('\n'));
console.log(out.join('\n').split('\n').slice(0, 200).join('\n'));
